language: node_js
node_js:
  - node
install:
  - yarn build
deploy:
  provider: s3
  local_dir: frontend/build
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: go-devel.flexcomply.com
  on:
    branch: devel
